#!/bin/bash

# exit on error
set -e
cd $HOME
# get the source code

git clone --depth 1 --branch 7.2.1 https://github.com/OSGeo/PROJ proj-src
cd proj-src
mkdir build
cd build
cmake ..
cmake --build .
cmake --build . --target install

cd $HOME


git clone --depth 1 --branch v3.5.3 https://github.com/OSGeo/gdal gdal-src
cd gdal-src
mkdir build
cd build
cmake ..
cmake --build .
cmake --build . --target install

cd $HOME

wget https://github.com/PDAL/PDAL/releases/download/2.3.0/PDAL-2.3.0-src.tar.bz2
tar -xvf PDAL-2.3.0-src.tar.bz2
cd PDAL-2.3.0-src
mkdir build
cd build
cmake ..
make
make install
cd $HOME







git clone --depth 1 --branch 8.3.1RC1 https://github.com/OSGeo/grass.git grass-src

# enter the directory with source code
cd grass-src

# compile
./configure \
    --enable-largefile=yes \
    --with-nls \
    --with-cxx \
    --with-readline \
    --with-bzlib \
    --with-pthread \
    --with-proj-share=/usr/share/proj \
    --with-geos=/usr/bin/geos-config \
    --with-cairo \
    --with-opengl-libs=/usr/include/GL \
    --with-freetype=yes --with-freetype-includes="/usr/include/freetype2/" \
    --with-sqlite=yes \
    --without-pdal
make

# leave the directory with source code
cd ..

# put command on path
# ensure the user specific bin dir exists (already on path)
mkdir -p $HOME/.local/bin/
# create link to build
ln -s $HOME/grass-src/bin.*/grass* $HOME/.local/bin/grass

# download a sample dataset
mkdir -p grassdata \
  && curl -SL https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.zip > nc_spm_08_grass7.zip \
  && unzip -qq nc_spm_08_grass7.zip \
  && mv nc_spm_08_grass7 grassdata \
  && rm nc_spm_08_grass7.zip
wget https://zenodo.org/record/6967699/files/FOSS4G_2022_GRASS_GIS_workshop.zip
unzip FOSS4G_2022_GRASS_GIS_workshop.zip
rm FOSS4G_2022_GRASS_GIS_workshop.zip
